[package]
name = "sui-replay-frontend"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false

[dependencies]
include_dir.workspace = true
open = "5.0.1"

